services:
  some-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
