jobId: ${jobId}
jobType: TASK_CREATOR
producerConfig:
  producerId: RDB_TASK_CREATOR
  connectionId: msSQLServerConnection
  jobs:
    - table: movies.title
      jobPrefix: movieTitleLoader-
      numJobs: 5
      config: JobConfig.yml
      loadQuery: "select * from (select Row_Number() over (order by (select 0)) as RowIndex, * from movies.title) as titles Where titles.RowIndex >= ${start} and titles.RowIndex <= ${end}"




